### ISSUE TITLE
Hoist [proofName]ABIEncoder.encodeAndExit() to top of validator contract

### ISSUE THREAD

**Issue by thomas-waite** [AztecProtocol/aztec-v1#150]
## Summary of issue
All zero-knowledge validator contracts (`JoinSplit.sol`, `PrivateRange.sol` etc.) currently validate a proof and then, if successfully validated, call the associated ABI encoder, via `[proofName]ABIEncoder.encodeAndExit()`. This is to encode the `proofOutputs` in a standardised format, compatible with the `ACE` and so generate the transfer instructions. 

To make the code functionality clearer this encoding function call should be hoisted to the start of the fallback function, immediately after `validatePrivateRange()`. 

## Next steps
Hoist for:
- [ ] `JoinSplit.sol`
- [ ] `BilateralSwap.sol`
- [ ] `DividendComputation.sol`
- [ ] `AdjustSupply.sol`
- [ ] `PrivateRange.sol`
- [ ] `PublicRange.sol`

**Comment by PaulRBerg** [comment]
My plan for this would be to reuse the code in the validators, perhaps using solidity libraries.
