### ISSUE TITLE
Running confidentialMint() causes either "Transaction ran out of gas" or "Block Gas Limit exceeded"

### ISSUE THREAD

**Issue by tezansahu** [AztecProtocol/aztec-v1#171]
## Current Behaviour

The confidentialMint() function in the ZkAssetMintable.sol that I deployed on Ropsten testnet causes the following error when called using web3: `Error: Transaction ran out of gas. Please provide more gas` in spite of providing gasLimit as 8000000 for Ropsten testnet (and on increasing the amount, it says `block Gas Limit exceeded`)

## Code in relevant files:

1.  The `truffle-config.js` file is as shown:
```javascript
require("dotenv").config();

const HDWalletProvider = require("truffle-hdwallet-provider");

const createProvider = (network) => {
  if (!process.env.MNEMONIC) {
    console.log("Please set your MNEMONIC in a .env file first");
    process.exit(1);
  }
  if (!process.env.INFURA_API_KEY) {
    console.log("Please set your INFURA_API_KEY in a .env file first");
    process.exit(1);
  }
  return () => {
    return new HDWalletProvider(
      process.env.MNEMONIC,
      `https://${network}.infura.io/v3/` + process.env.INFURA_API_KEY
    );
  };
};

module.exports = {
  networks: {
   
    development: {
     host: "127.0.0.1",     // Localhost (default: none)
     port: 8545,            // Standard Ethereum port (default: none)
     network_id: "*",       // Any network (default: none)
    },

    rinkeby: {
      provider: createProvider("rinkeby"),
      network_id: 4,       // Rinkeby's id
      gas: 10000000,        // Rinkeby has a lower block limit than mainnet
      skipDryRun: true     // Skip dry run before migrations? (default: false for public nets )
    },
    ropsten: {
      provider: createProvider("ropsten"),
      network_id: 3,       // Ropsten's id
      gas: 8000000,        // Ropsten has a lower block limit than mainnet
      skipDryRun: true     // Skip dry run before migrations? (default: false for public nets )
    },
  },

  mocha: {
    
  },


  compilers: {
    solc: {
      version: "0.5.2"
    }
  }
}
```

2.  The `test.js` file is as shown:
```javascript
const Web3 = require("web3");
const Tx = require("ethereumjs-tx");
require("dotenv").config();

const url = `https://ropsten.infura.io/v3/${process.env.INFURA_API_KEY}`;
const web3 = new Web3(new Web3.providers.HttpProvider(url));

const { note, proof, abiEncoder } = require('aztec.js');
const aztecArtifacts = require("@aztec/contract-artifacts");
const { getContractAddressesForNetwork, NetworkId } = require("@aztec/contract-addresses");
const secp256k1 = require('@aztec/secp256k1');

aztecAddresses = getContractAddressesForNetwork(NetworkId.Ropsten);

ace = new web3.eth.Contract(aztecArtifacts.ACE.abi, aztecAddresses.ACE);
joinSplit = new web3.eth.Contract(aztecArtifacts.JoinSplit.abi, aztecAddresses.JoinSplit);
erc20Mintable = new web3.eth.Contract(aztecArtifacts.ERC20Mintable.abi, aztecAddresses.ERC20Mintable);
confidentialToken = new web3.eth.Contract(aztecArtifacts.ZkAssetMintable.abi, process.env.CONFIDENTIAL_TOKEN_ADDRESS_ROPSTEN);

let proofs = []
const aztecAccounts = [secp256k1.generateAccount(), secp256k1.generateAccount()];

async function mintNotes() {
    let my_notes = [note.create(aztecAccounts[0].publicKey, 50), 
        note.create(aztecAccounts[0].publicKey, 0), 
        note.create(aztecAccounts[0].publicKey, 30), 
        note.create(aztecAccounts[0].publicKey, 20)]

    let account= {
        address:"0x0aFd127a0d25A4f628DcaA70781b4d3cDb4482D6",
        pvtKey: //my private key
    };

    proofs[0] =  proof.mint.encodeMintTransaction({
        newTotalMinted: my_notes[0],
        oldTotalMinted: my_notes[1],
        adjustedNotes: my_notes.slice(2,4),
        senderAddress: account.address})


    const MINT_PROOF = 66049;

    let proofOutputs = await ace.methods.validateProof(MINT_PROOF, account.address, proofs[0].proofData).call()

    let data = confidentialToken.methods.confidentialMint(MINT_PROOF, proofs[0].proofData).encodeABI();
    const nonce = await web3.eth.getTransactionCount(account.address, "pending");
    const rawTransaction = {
        "nonce" : nonce,
        "from" : account.address,
        "to" : process.env.CONFIDENTIAL_TOKEN_ADDRESS,
        "value" : "0x0",
        "gasLimit" : web3.utils.toHex(8000000),
        "gasPrice" : web3.utils.toHex(20* 1e9),
        "data" : data,
        "chainId" : web3.utils.toHex(await web3.eth.net.getId())
    };

    var txn = new Tx(rawTransaction);
    txn.sign(Buffer.from(account.pvtKey, "hex"))

    web3.eth.sendSignedTransaction('0x'+txn.serialize().toString('hex')).on('transactionHash',console.log);

}

mintNotes()
```

## My Environment

-   AZTEC packages and their versions:
    "@aztec/contract-addresses": "^1.4.0"
    "@aztec/contract-artifacts": "^1.9.1"
    "@aztec/dev-utils": "^1.8.0"
    "@aztec/protocol": "^0.6.0"
    "@aztec/secp256k1": "^1.0.0"
    "@aztec/typed-data": "^1.0.0"
    "aztec.js": "^0.7.0",
-   Node and yarn version: v10.15.0 and 1.15.2 respectively
-   Truffle version: v5.0.0 
-   Operating System and version: Ubuntu 16.04

**Comment by PaulRBerg** [comment]
Hey @tezansahu, thank you for providing a detailed log of what happened. Unfortunately, I am not able to infer what went awry, but I do want to apologise because our npm package versions are not fully stable as of now (we haven't released v1.0 of the protocol). That means that it's likely there are going to be breaking changes between MINOR or PATCH versions. I recommend removing the caret (^) from your `package.json` AZTEC modules in the interim.

Something that doesn't look right to me though is the following:

- CONFIDENTIAL_TOKEN_ADDRESS_ROPSTEN
- CONFIDENTIAL_TOKEN_ADDRESS

It seems you're using two different environment variables.

**Comment by tezansahu** [comment]
Thanks for the reply. As far as the environment variable is concerned, this is a typo. I have actually used only one variable. Although thanks for pointing it out.

Could you let me know the approximate dates by which you would officially launch the stable v1.0 of the protocol?

PS: This issue is not only on Ropsten. I have tried deployment on Rinkeby as well as Truffle Deveopment networks. It causes the same issue there.

**Comment by PaulRBerg** [comment]
Hey, please pardon my long delay. I tried to reproduce the bug but no luck. If it is not too much to ask, do you think you could pull together a GitHub repo or a CodeSandbox project? Or, at the very least, share the ZkAssetMintable contract address?

That said, I did stumble upon a few red flags while inspecting your code:

### Gas Limit

Even if you have issues with the gas limit, it's not recommended to increase it beyond the known upper bound.

### Solidity Version

You seem to be using solidity`0.5.2`, which is not compatible with our smart contracts:

```
@aztec/protocol/contracts/ACE/NoteRegistry.sol:262:30: Warning: The "shr" instruction is only available for Constantinople-compatible VMs. You are currently compiling for "byzantium", where it will be interpreted as an invalid instruction.
            createdOn := and(shr(8, note), 0xffffffffff)
```

**Comment by tezansahu** [comment]
Thanks for the reply.

I have just tried to compile the contracts using `solidity 0.5.7` (which seems to be the one that AZTEC contacts are compatible with, as shown in the compiler config in the repo) and deployed them on Rinkeby using Remix. The following are the addresses:
* `ACE.sol` : `0x2c0f0417224860d9f822003df8a083cedcf89ff1`
* `my_ZkAssetMintable.sol` : `0x861981d2df8ce63a768d7af6db31e3567d612c9a`

Following is the procedure that I followed to obtain the proofData to be sent as a parameter for the confidentialMint() in Remix:

```javascript
const { note, proof } = require('aztec.js');
const secp256k1 = require("@aztec/secp256k1")
const aztecAccounts = [secp256k1.generateAccount(), secp256k1.generateAccount()];
var newTotalMinted = await note.create(aztecAccounts[0].publicKey, 50)
var oldTotalMinted = await note.createZeroValueNote()
var newNote = await note.create(aztecAccounts[0].publicKey, 50)
var adjustedNotes = [newNote]
var mintProof = proof.mint.encodeMintTransaction({newTotalMinted, oldTotalMinted, adjustedNotes, senderAddress: "0x0aFd127a0d25A4f628DcaA70781b4d3cDb4482D6"}) // Here, sender address is my Ethereum Address on Rinkeby, which has test Ether
var proofData = mintProof.proofData
```

The proof data that I obtained is as follows: `0x29c96394b6447085dff92ae570d11ca24675e251725e9ee9d210e53392ebc17300000000000000000000000000000000000000000000000000000000000000c00000000000000000000000000000000000000000000000000000000000000320000000000000000000000000000000000000000000000000000000000000036000000000000000000000000000000000000000000000000000000000000003c000000000000000000000000000000000000000000000000000000000000000030c8fbd9c277a29cd7b1c7601158704cc0a25c2745c7e8ada71e3e776935529aa1c8f8127458267b5e4a4dd14792964035e9dabbad69888cd128c897fe833971807e88226426aba4829d45d30a006e3835317f3d22fc2c3a98ebef03af51954fb256a702b118abc6a40adf5ff92e8d0b1951a2885c97a1f7afef89e10da2f02921b5bb5c5323bf3fc9717659115335df39011f4cf1dc2a921b1a61650dd3b1a0e0c096e8aa8fd797551f47232df46a84253da50e987bab56be8faf8b7d59ef3e71e476e32d3efee2e8d143a41c33552b87ef7672b58b989f1bb1032bdaea7203312fc6498896f0bb3bc13091dc5f1d33f94d5a654c8dd99afb888980cf79551540de622ec1ab9f9cca4760fc85decee60e2bc80d1f9f384c07f3b2f9f7d2aac6c24ada3e551558e69e8f8ee7632b11320b92db30e00229b4feb62c73ad592372410f7463e3bdb09c66bcc67cbd978bb8a2fd8883782d177aefc6d155391b1d1b812c4f960e11ba5bf0184d3433a98127e90a6fdb2d1f12cdb369a5d3870866627000000000000000000000000000000000000000000000000000000000000000011ceee534675b6aa659c7d7363d6c5717853f78dc78c694065388f20dd5e24a10006a0860854b7fe3f47f54ac4c5395873557f4fe26f8cab2d3e2f343eb0bcb230554433514f2783766ad5d1fc39712e39d2913f4ec0b008c2774271a578e5eb0c46e327f69195e9ba72cf984d0915065cdd22c31ed3f9ddb9225454bec3f40326dbf5fd4231c2f367957e91e5ee188de03923c6b576f50beb00eb0f5c25ca45000000000000000000000000000000000000000000000000000000000000000100000000000000000000000026b8ab424276a6751a49ce8ed190acbd2a390cfc0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000000000000000000000000000026b8ab424276a6751a49ce8ed190acbd2a390cfc00000000000000000000000000000000000000000000000000000000000000e20000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000008000000000000000000000000000000000000000000000000000000000000000c10000000000000000000000000000000000000000000000000000000000000021eff9beac9595f45cf86e1d9864f1d3d9460b77a74cb6fbcbd796fd877ef34b34000000000000000000000000000000000000000000000000000000000000000021cb80528cb0b2e0a84f7130a2a3645705bbffb4d9899b3b241f1bb496411d935a00`

On passing this, and the mint proof ID (ie, 66049) to the confidentialMint(), it still gives me the error: `Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending? gas required exceeds allowance (7003096) or always failing transaction`

Requesting you to help me out in understanding what is going wrong.

**Comment by tezansahu** [comment]
@PaulRBerg please let me know the issue in the code above.
Regards.

**Comment by ArnSch** [comment]
Solved via email a couple days ago, working script posted below.

``` const Web3 = require("web3");
const Tx = require("ethereumjs-tx");
require("dotenv").config();

const url = `https://ropsten.infura.io/v3/${process.env.INFURA_API_KEY}`;
const web3 = new Web3(new Web3.providers.HttpProvider(url));


const { note, proof } = require('aztec.js');
const aztecArtifacts = require("@aztec/contract-artifacts");
const { getContractAddressesForNetwork, NetworkId } = require("@aztec/contract-addresses");
const secp256k1 = require('@aztec/secp256k1');

aztecAddresses = getContractAddressesForNetwork(NetworkId.Ropsten);

ace = new web3.eth.Contract(aztecArtifacts.ACE.abi, aztecAddresses.ACE);
joinSplit = new web3.eth.Contract(aztecArtifacts.JoinSplit.abi, aztecAddresses.JoinSplit);
erc20Mintable = new web3.eth.Contract(aztecArtifacts.ERC20Mintable.abi, aztecAddresses.ERC20Mintable);
confidentialToken = new web3.eth.Contract(aztecArtifacts.ZkAssetMintable.abi, process.env.PURE_ZKASSET_ROPSTEN);

const aztecAccounts = [secp256k1.generateAccount(), secp256k1.generateAccount()];

async function mintNotes() {
    let my_notes = [await note.create(aztecAccounts[0].publicKey, 50),
        // For the first mint operation, the 'totalMinted' note which is on-chain is this special zero-value note
        await note.createZeroValueNote(), 
        await note.create(aztecAccounts[0].publicKey, 30), 
        await note.create(aztecAccounts[0].publicKey, 20)]

    let account= {
        address: process.env.PUBLIC_KEY,
        pvtKey: process.env.PVT_KEY
    };

    const proof =  proof.mint.encodeMintTransaction({
        newTotalMinted: my_notes[0],
        oldTotalMinted: my_notes[1],
        adjustedNotes: my_notes.slice(2,4),
        // This is confusing, but this is used for signatures and needs to be the address of the contract sending the proof to ACE
        // (i.e.) the token contract
        senderAddress: confidentialToken.address})

    console.log("....", confidentialToken.address)

    console.log("Proof Data: ", proof.proofData)

    const MINT_PROOF = 66049;

    let data = confidentialToken.methods.confidentialMint(MINT_PROOF, proof.proofData).encodeABI();
    const nonce = await web3.eth.getTransactionCount(account.address);
    const rawTransaction = {
        "nonce" : nonce,
        "from" : account.address,
        "to" : confidentialToken.address,
        "value" : "0x0",
        "gasLimit" : web3.utils.toHex(6000000),
        "gasPrice" : web3.utils.toHex(10* 1e9),
        "data" : data,
        "chainId" : web3.utils.toHex(await web3.eth.net.getId())
    };

    var txn = new Tx(rawTransaction);
    txn.sign(Buffer.from(account.pvtKey, "hex"))
    web3.eth.sendSignedTransaction('0x'+txn.serialize().toString('hex')).on('transactionHash',console.log);
     
    console.log("done")
}

mintNotes()

```
