### ISSUE TITLE
@aztec/contract-artifacts 1.12.2 cannot be required on node.js

### ISSUE THREAD

**Issue by yurenju** [AztecProtocol/aztec-v1#348]
@aztec/contract-artifacts does not work at all.

```shell
$ npm init -y
$ yarn add @aztec/contract-artifacts
$ vim test.js
```

just require `@aztec/contract-artifacts`:
```javascript
require("@aztec/contract-artifacts");
```

## Expected Behaviour
can be required
## Current Behaviour
```shell
$ node test.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../artifacts/AdjustSupply'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/Users/yurenju/Downloads/test/node_modules/@aztec/contract-artifacts/lib/index.js:6:20)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```

## Possible Solution
I believe it was solved in latest version on github, possible solution is just bump a version with latest source code.
## Your Environment

-   AZTEC packages and their versions: "@aztec/contract-artifacts": "^1.12.2"
-   Node and yarn version: v10.16.3
-   Truffle version: v5.0.39
-   Lerna version: N/A
-   Operating System and version: MacOS 10.14.6

**Comment by thomas-waite** [comment]
Thanks for raising this @yurenju !  I'll take a look now and have a fix out later today or tomorrow

**Comment by thomas-waite** [comment]
Hey @yurenju all done. I've made the fix and published a new package with a bumped version. The package you need is now **@aztec/contract-artifacts@1.12.3**. 

If you could `require` it and let me know that it works for you, I'll then close the issue. Thanks again for flagging this.

**Comment by yurenju** [comment]
@thomas-waite @aztec/contract-artifacts@1.12.3 is not published on npm, I suggest to re-open this issue.

https://www.npmjs.com/package/@aztec/contract-addresses

**Comment by thomas-waite** [comment]
hey @yurenju , I think you accidentally linked to the `contract-addresses` npm package. You should be able to see the new `contract-artifacts` package here: 

https://www.npmjs.com/package/@aztec/contract-artifacts

Let me know that that's all good

**Comment by yurenju** [comment]
No I need `@aztec/contract-addresses` for testing on rinkeby, that's why I need addresses pacakge :D

**Comment by thomas-waite** [comment]
Hi @yurenju  not sure I fully understand your question, the latest versions and npm links for the different `contract-addresses` and `contract-artifacts` packages are:
- `contract-addresses` - _version_: **1.7.2**, _npm_: https://www.npmjs.com/package/@aztec/contract-addresses
- `contract-artifacts`- _version_: **1.12.3**, _npm_: https://www.npmjs.com/package/@aztec/contract-artifacts

You correctly found a problem with the `contract-artifacts` package. It's now fixed and a new version has been published as 1.12.3. Thanks for spotting it.

If you've come across a bug with the `contract-addresses` package, please could you open a seperate issue and I'll take a look.

Feel free to dm me on our AZTEC discord channel: https://discord.gg/CgpYpj if you have any more questions

**Comment by yurenju** [comment]
oh sorry I just got confused since I was using both of artifacts and addresses packages, and you are right I should try new version of `contract-artifacts`. Thank you so much!

**Comment by thomas-waite** [comment]
No worries, pleased I could be of help! Feel free to keep me updated as to how you get on and ask any more questions you have in discord
