### ISSUE TITLE
Get all Aztec notes for an account.

### ISSUE THREAD

**Issue by utkmaheshwari245** [AztecProtocol/aztec-v1#360]
Given an account, is there a way to get all the Aztec notes owned by that account ?

**Comment by thomas-waite** [comment]
Hey @utkmaheshwari245  thanks for the question. 

If you could head over to our Discord channel, https://discord.gg/q9RWNP, I'll be very happy to answer your question there and give any other help that's required.

**Comment by utkmaheshwari245** [comment]
It seems that the invite has expired !
Could you please send me another invite ?
Thanks

**Comment by thomas-waite** [comment]
Sure, thanks for pointing that out. This link shouldn't expire: https://t.co/Fuq0VjfjW6
