### ISSUE TITLE
Spending key for an aztec note

### ISSUE THREAD

**Issue by utkmaheshwari245** [AztecProtocol/aztec-v1#361]
aztec.note.derive() function requires the spending key of a note. How do I calculate that spending key ?

**Comment by thomas-waite** [comment]
Hey @utkmaheshwari245 , thanks again for these questions that you're posting. 

I'll be very happy to help answer them - please go ahead and join our Discord server and head to the _Technical_ channel. Here's an invite link: https://discord.gg/q9RWNP

**Comment by utkmaheshwari245** [comment]
It seems that the invite has expired !
Could you please send me another invite ?
Thanks

**Comment by thomas-waite** [comment]
I've replied on the other issue too, thanks for pointing that out. This link shouldn't expire: https://t.co/Fuq0VjfjW6
