### ISSUE TITLE
LibEIP712.recoverSignature() allows to replay signatures just changing the size of the signature parameter

### ISSUE THREAD

**Issue by gustavo-grieco** [AztecProtocol/aztec-v1#453]
The `recoverSignature()` function allows to check for message signatures using the `ecrecover` precompiled contract:

https://github.com/AztecProtocol/AZTEC/blob/5c70d6bb85b83c002e59ef2ca65d20e66e3f097c/packages/protocol/contracts/libs/LibEIP712.sol#L72-L79

However, the implementation permits signatures with two different sizes: `0x41` bytes and `0x60` bytes.

https://github.com/AztecProtocol/AZTEC/blob/5c70d6bb85b83c002e59ef2ca65d20e66e3f097c/packages/protocol/contracts/libs/LibEIP712.sol#L118-L128

This allows an attacker to replay an signature, just changing the size of the `_signature` dynamic array. On one hand, if the original `_signature` parameter had `0x41` bytes, an attacker can extend it to have `0x60` bytes and it should be correctly validated by `recoverSignature`. On the other hand, if the original `_signature` had `0x60` bytes, an attacker could declare as smaller one (`0x41` bytes) but send extra data in the transaction. Since the function is written in assembly, the code will access the extra data and the replayed signature will be validated by `recoverSignature`.

The PR #447 fixes this issue.

**Comment by ArnSch** [comment]
Addressed in #447
