### ISSUE TITLE
Behaviour20200106.initialize can be front-runned to block the correct deployment

### ISSUE THREAD

**Issue by gustavo-grieco** [AztecProtocol/aztec-v1#456]
The initialization of `Behaviour20200106` contract (or any future implementation) requires to call the `initialize` function with suitable parameters:

https://github.com/AztecProtocol/AZTEC/blob/8657927b62fd1f14e2eb0a3205147b4163328987/packages/protocol/contracts/AccountRegistry/epochs/20200106/Behaviour20200106.sol#L64-L68

However, there is no access control in place to avoid an attacker to front-run this call. As a result of that, an attacker could temporarily block the initialization front-running each deployment, using invalid parameters in the `initialize` call.

It is recommended to carefully document this potential issue to use an extra amount of gas during the deployment.

**Comment by thomas-waite** [comment]
Have documented and linked back to this issue in the main protocol `specification` : https://github.com/AztecProtocol/specification/blob/master/README.md#potential-issues-to-be-aware-of
