### ISSUE TITLE
registerAZTECExtension can be front-runned with a different spending public key

### ISSUE THREAD

**Issue by gustavo-grieco** [AztecProtocol/aztec-v1#459]
The `registerAZTECExtension` function allows to register a new AZTEC account and associate it with a spending public key:

https://github.com/AztecProtocol/AZTEC/blob/8657927b62fd1f14e2eb0a3205147b4163328987/packages/protocol/contracts/AccountRegistry/epochs/20200106/Behaviour20200106.sol#L101-L124

The registration is protected by the signature verification implemented by `recoverSignature` function. However, the parameter defining the associated spending public key (`_spendingPublicKey`) is not included in the signature verification:

https://github.com/AztecProtocol/AZTEC/blob/8657927b62fd1f14e2eb0a3205147b4163328987/packages/protocol/contracts/AccountRegistry/epochs/20200106/Behaviour20200106.sol#L114-L117

This allows an attacker to potentially front-run a `registerAZTECExtension` transaction before it is confirmed by the network. As a result of that, the attacker can easily replace the `_spendingPublicKey` by another to cause an undesired effect for the victim user.

The PR #455 fixes this issue.

**Comment by ArnSch** [comment]
Addressed in #455
