### ISSUE TITLE
`balanceOfLinkedToken` returns an overflown number

### ISSUE THREAD

**Issue by fvictorio** [AztecProtocol/aztec-v1#468]
## Expected Behaviour

`balanceOfLinkedToken` should return a BigNumber or string

## Current Behaviour

`balanceOfLinkedToken` returns a javascript number, which may overflow

## Possible Solution

I think the customary thing to do here is to return some instance of some big number library, but returning a string should work too.

## Steps to Reproduce (for bugs)

1. Create a zkAsset in Rinkeby with the address from the docs: `const asset = await window.aztec.zkAsset('0x70c23EEC80A6387464Af55bD7Ee6C8dA273C4fb4');`
2. Mint a huge amount of the linked token (`0x5B7825EA998Db74E7e43736D91459C1B0f0AdcA9`). I did `10000000000000000000` (1E19)
3. Call `asset.balanceOfLinkedToken()`

## Your Environment

I used the aztec library from `https://sdk.aztecprotocol.com/aztec.js`

**Comment by joeandrews** [comment]
Thanks for reporting this, @LeilaWang is looking into it. I think your solution of returning a BigNumber should be sufficient.

**Comment by joeandrews** [comment]
:tada: This issue has been resolved in version 1.19.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This issue has been resolved in version 1.5.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This issue has been resolved in version 1.7.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This issue has been resolved in version 0.17.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This issue has been resolved in version 1.18.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This issue has been resolved in version 2.4.0 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This issue has been resolved in version 1.3.2 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:

**Comment by joeandrews** [comment]
:tada: This issue has been resolved in version 1.1.4 :tada:

Your **[semantic-release](https://github.com/semantic-release/semantic-release)** bot :package::rocket:
