### ISSUE TITLE
Project Depreciated Warning

### ISSUE THREAD

**Issue by notjustinshaw** [AztecProtocol/aztec-v1#663]
Hey team!

I was working through the sdk and I seem to be having the same issue in several repositories (sdk-starter-kit and the live example on the docs: https://docs.aztecprotocol.com/#/SDK/Getting%20started). Both cases show the same "project depreciated" warning below. Is this expected?
<img width="342" alt="Screen Shot 2021-09-01 at 8 53 24 AM" src="https://user-images.githubusercontent.com/46334750/131704018-679742ac-22f4-480f-9e8a-c966c8ba8db9.png">

**Comment by joeandrews** [comment]
Hi @justinalexandershaw you need the new SDK [here](https://developers.aztec.network/) let us know if you have any issues!

Thanks

Joe

**Comment by notjustinshaw** [comment]
That looks more familiar! I had used that link originally, and was wondering why the docs suddenly looked a lot older =)

Thanks,

Justin
